version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-lts
    ports:
      - "8080:8080"
      - "50000:50000"
    group_add:
      - 0
    volumes:
      - /home/karim/Desktop/Jenkins/Jenkins-data/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  sonarqube:
    image: sonarqube:lts-community
    ports:
      - "9000:9000"
    restart: unless-stopped

