microServiceName: recommendationservice
replicaCount: 2
serviceImageName: gcr.io/google-samples/microservices-demo/recommendationservice
serviceImageTag: v0.2.3
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"
- name: DISABLE_DEBUGGER
  value: "1"
serviceType: ClusterIP
servicePort: 8080