microServiceName: emailservice
replicaCount: 2
serviceImageName: gcr.io/google-samples/microservices-demo/emailservice
serviceImageTag: v0.2.3
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1" 
serviceType: ClusterIP
servicePort: 5000