apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microServiceName }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Values.microServiceName }}
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
      name: {{ .Values.microServiceName }}
