apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-service-monitor
  labels:
    app: prometheus
    release: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
      port: app
      path: /metrics
  selector:
    matchLabels:
      app: appservice
